platform :ios, '9.0'
use_frameworks!

target 'NEMCore' do

  #pod 'CryptoCore', :path => '../'

  pod 'CryptoCore', :git => 'https://github.com/a-melnichuk/CryptoCore.git'
  
  target 'NEMCoreTests' do
    inherit! :search_paths
  end

end
