platform :ios, '9.0'
use_frameworks!

target 'Examples' do
  pod 'CryptoCore', :path => '../../'
  #pod 'CryptoCore', :git => 'https://github.com/a-melnichuk/CryptoCore.git'
  pod 'TRONCore', :path => '../../'
  pod 'secp256k1-extended', :path => '../../'
  #pod 'TRONCore', :git => 'https://github.com/a-melnichuk/CryptoCore.git'

  target 'ExamplesTests' do
    inherit! :search_paths
  end

end
