platform :ios, '9.0'
use_frameworks!

target 'EthereumCore' do

  pod 'web3swift.pod'
  pod 'CryptoCore', :path => '../'
  #pod 'CryptoCore', :git => 'https://github.com/a-melnichuk/CryptoCore.git'
  
  target 'EthereumCoreTests' do
    inherit! :search_paths
  end

end
